name: Rishi Sharma
favicon: null
layout_spectrum: 0.5609007740858942
typography_spectrum: 0.3724499740637839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6889845498371869
  lightness: 0.8372560555581003
  saturation: 0.2568828873336315
  rhythmicContrast: 0.23300640634261072
purpose: []
